# Generated by Django 2.0.5 on 2018-05-31 12:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(default='', max_length=50)),
                ('area_desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Beta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beta_name', models.CharField(default='', max_length=50)),
                ('beta_desc', models.CharField(default='', max_length=500)),
                ('quality_rating', models.IntegerField(default=0)),
                ('creator_name', models.CharField(default='', max_length=50)),
                ('set_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date set')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(default='Missing location name', max_length=50)),
                ('longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('location_desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(default='', max_length=50)),
                ('setter_name', models.CharField(default='', max_length=100)),
                ('grade', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('set_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date set')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beta.Area')),
            ],
        ),
        migrations.AddField(
            model_name='beta',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beta.Route'),
        ),
        migrations.AddField(
            model_name='area',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beta.Location'),
        ),
    ]
