# Generated by Django 2.0.5 on 2018-05-14 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beta_text', models.CharField(max_length=200)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beta.Area')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
