# Generated by Django 2.0.5 on 2018-05-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0002_auto_20180514_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='area_text',
            new_name='area_name',
        ),
        migrations.RenameField(
            model_name='beta',
            old_name='beta_text',
            new_name='beta_name',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='route_text',
            new_name='route_name',
        ),
    ]
