# Generated by Django 2.0.5 on 2018-05-31 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0002_auto_20180531_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='area_desc',
        ),
    ]
