# Generated by Django 2.0.5 on 2018-05-31 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0003_remove_area_area_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='setter_name',
        ),
    ]
