# Generated by Django 2.0.5 on 2018-05-14 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0003_auto_20180514_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='pub_date',
        ),
    ]
