# Generated by Django 2.0.5 on 2018-05-31 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0004_remove_route_setter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='route',
            name='longitude',
        ),
    ]
