# Generated by Django 2.0.5 on 2018-05-14 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0004_remove_location_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beta',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beta.Route'),
        ),
    ]
