# Generated by Django 2.0.5 on 2018-05-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0005_auto_20180514_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='beta',
            name='beta_text',
            field=models.CharField(default='Default beta text', max_length=500),
            preserve_default=False,
        ),
    ]
