# Generated by Django 2.0.5 on 2018-05-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0006_remove_beta_beta_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='beta',
            name='beta_desc',
            field=models.CharField(default='', max_length=500),
        ),
    ]
