# Generated by Django 2.0.5 on 2018-06-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0008_auto_20180602_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='route',
            name='longitude',
        ),
        migrations.AddField(
            model_name='area',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='area',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
